### ISSUE TITLE
Output exr file generated is very dark

### ISSUE THREAD

**Issue by ChannuAlmace** [Wanggcong/StyleLight#11]
I just cloned this repo and tried running the code as per the instructions in Ubuntu. The code executed successfully, but the output exr file that is generated is very dark. It is not as per the outputs shown in the paper. Am I missing something here or have I setup the environment improperly?

I used the test images residing at https://github.com/Wanggcong/StyleLight/tree/main/assets/wild2.

I am quite new to the HDR domain and would really appreciate some help.

Thank you!

**Comment by will876** [comment]
Hi, I have the same problem. Have you solved it?
