### ISSUE TITLE
Evaluating the pretrained model

### ISSUE THREAD

**Issue by tonetechnician** [Wanggcong/StyleLight#2]
Hey there @Wanggcong 

Thanks so much for making this repo available. It has been very interesting to explore! 

I've been evaluating your pretrained model on some of the Laval dataset - I'm noticing in the paper you get quite close to ground truth results.

<img width="829" alt="image" src="https://user-images.githubusercontent.com/13471797/232311597-bc42c958-f2ba-4dc3-81a3-47b995f0671f.png">

Whilst evaluating the model + code, I've been noticing that I'm struggling quite a lot to get close to ground truth. I've attempted various hyperparameter configurations. All the examples generated below were done with 600 steps on the projection step (generating the latent code) and 350 steps on the inversion (usually reaches the lpips threshold early, around 30-100 steps)

The crop2pano is set to 60 degrees for the fov and aspect ratio of the input is maintained but scaled down to fit in 480p 

Here are some attached examples: 

Input:

1.
![9C4A2495-40e081c571](https://user-images.githubusercontent.com/13471797/232312071-c65e68f1-0540-41b8-9953-1b3aa6d95213.png)

2.
![9C4A1998-f2e3c43f1e](https://user-images.githubusercontent.com/13471797/232312111-b3b09815-a4e2-4ada-a6b1-f45e63fc7509.png)

3.
![9C4A2509-ad1651abdf](https://user-images.githubusercontent.com/13471797/232312115-719c3c9a-89ce-422c-8bc8-88a4c13e3c3c.png)

4.

![test](https://user-images.githubusercontent.com/13471797/232313155-dc814077-e98b-4fc1-94b7-010e446c5c42.png)

Ground truth:

1.
<img width="1692" alt="image" src="https://user-images.githubusercontent.com/13471797/232311883-c4ae85b0-fc03-4528-aefa-a97eb2abb668.png">

2.

<img width="1691" alt="image" src="https://user-images.githubusercontent.com/13471797/232312361-4fbb138e-9838-422b-9199-f1f0af414663.png">

3.
<img width="1689" alt="image" src="https://user-images.githubusercontent.com/13471797/232312281-1971acf6-d3be-44df-8005-135aaa6aafb0.png">

4.
![9C4A0205-437172d8ee](https://user-images.githubusercontent.com/13471797/232313207-8dcc34bc-be41-49e8-8a95-6c5b09c4828f.png)

Generated: 
1.
![image](https://user-images.githubusercontent.com/13471797/232311972-ec662198-59bf-4709-a078-790d48bcc12e.png)

2.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/13471797/232312411-12f3daa2-7594-44bb-8731-139c60b549a4.png">

3.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/13471797/232312537-97f6d2ff-a010-4f59-b95b-3d8936bca040.png">

4.

<img width="512" alt="image" src="https://user-images.githubusercontent.com/13471797/232313354-dd0f1f48-7c36-410e-b714-e75b20421a07.png">

I was wondering if you had any thoughts on what may be going wrong, or anything that can be modified to make the output more consistent with ground truth?

Many thanks in advance

**Comment by Wanggcong** [comment]
Hi, thanks for your attention. The goal of StyleLight is to generate plausible lighting given a FOV image.  It could be hard to recover a consistent pixel-level indoor scene with ground truth.

**Comment by tonetechnician** [comment]
Thanks @Wanggcong for your response! 

Yeah, I totally understand. I'm just wondering why your examples are getting closer to ground truth than mine. Do you think there is a parameter that is different? Particularly looking at example 4 as I believe it's the same input as your example the paper

**Comment by Wanggcong** [comment]
Two steps are considered after HDR generation. First, I remove the back strips at the bottom of the panoramas. Second, I wrap the panoramas just like [Gardner et al. Learning to Predict Indoor Illumination from a Single Image, SIGGRAPH Asia, 2017.](http://vision.gel.ulaval.ca/~jflalonde/publications/projects/deepIndoorLight/index.html).

For the second point, it is assumed that the object could not be placed at the center. Note that in a panorama, the camera is placed at the center of a sphere. If we would like to render an object far from the center, we need to warp the panorama to a new center. I would like to share this [code](https://github.com/Wanggcong/StyleLight/blob/main/warping.py) if it is the problem you are interested in.

As I can see, example 4  you show is the warpping problem.

I am glad to help you if you have any questions.

**Comment by Wanggcong** [comment]
Hi, if you have no other questions, I will close this issue. If any, you can re-open this issue or open a new issue. Thank you.

**Comment by Wanggcong** [comment]
Hi, if you have no other questions, I will close this issue. If any, you can re-open this issue or open a new issue. Thank you.
