### ISSUE TITLE
The evaluation include Angular Error, RMSE, siRMSE and FID.

### ISSUE THREAD

**Issue by asmile201711360030** [Wanggcong/StyleLight#4]
hi,I want to know where is the code for calculating MSE and RMSE？

**Comment by Wanggcong** [comment]
Please check our [Evaluation](https://github.com/Wanggcong/StyleLight/blob/main/evaluation/fast_rmse.py) for siMSE and RMSE. For FID, please find the evaluation at [this link](https://github.com/mseitzer/pytorch-fid).

**Comment by asmile201711360030** [comment]
Thanks,I have a new question. The MSE in the EMLight paper is on the order of 0.01, while the MSE in your paper is on the order of 0.1. Why is it different？

**Comment by Wanggcong** [comment]
> Thanks,I have a new question. The MSE in the EMLight paper is on the order of 0.01, while the MSE in your paper is on the order of 0.1. Why is it different？

Thanks for the question. 1) Since the parameters of three spheres (material) in EMLight are not released, we set our spheres for rendering. 2) We mask the spheres for evaluation while EMLight computes MSE for the whole image.

**Comment by asmile201711360030** [comment]
I have a new question.I used your rendering code and rendered it using  HDR images, resulting in an RMSE result of 0.01 level. I am learning about rendering. Do you think there is a problem with this approach?

**Comment by Wanggcong** [comment]
Sorry, without more detailed description, it could be hard to find the main problem. For example, different spheres with different materials would significantly different results.

One way to debug your result is to visualize rendered results with ground-truth HDR images and your generated HDR images.

**Comment by Wanggcong** [comment]
If there are no other questions, I will close this issue. You may re-open or open a new issue if any.
