### ISSUE TITLE
How to get the light direction of an FOV image?

### ISSUE THREAD

**Issue by yang-ruixin** [Wanggcong/StyleLight#5]
Dear authors,

Thanks for your great work.

Sorry to bother you, I have a few questions.

1. After running test_lighting.py, I can get the panorama, but how can I get the light direction (and also intensity) of the input FOV image? In simple words, my need is, input a image, and I want to know the light direction of this image. For multiple light sources or without a main light source, is there a way to get the light direction and intensity per pixel level of the input FOV image?

2. What is the best size of the input FOV image for test_lighting.py, or the best ratio of width/height, for example width/height=2?

3. In terms of application on face relighting, how can I get faces like in Fig. 14 in your paper? I mean, is the input a cropped and aligned face? Is the same trained model that you offered on Google Drive? After running test_lighting.py, I get the panorama with a face in the center, and then what should I do to get faces like in Fig. 14?

Thanks in advance.

**Comment by Wanggcong** [comment]
Thank you for you attention.
1. Given a LDR FOV image, we generate a HDR panorama. The HDR panorama is a HDR spherical image that provides lighting direction and HDR provides lighting intensity.

2. Since our model uses GAN inversion, the size of FOV is not limited to a fixed size, see the [framework](https://style-light.github.io/index). Given a FOV, we project it into a panorama, where black areas are invisible regions and visible pixels are from FOV. We then use GAN inversion to generate HDR panoramas.

3. We use  [this paper, code](https://elliottwu.com/projects/20_unsup3d/) to generate faces.  When you have both HDR panorams and 3D faces, you can render the faces with blender app or blender script. I suggest this [blender script](https://github.com/yuki-koyama/blender-cli-rendering).

**Comment by yang-ruixin** [comment]
> Thank you for you attention.
> 
> 1. Given a LDR FOV image, we generate a HDR panorama. The HDR panorama is a HDR spherical image that provides lighting direction and HDR provides lighting intensity.
> 2. Since our model uses GAN inversion, the size of FOV is not limited to a fixed size, see the [framework](https://style-light.github.io/index). Given a FOV, we project it into a panorama, where black areas are invisible regions and visible pixels are from FOV. We then use GAN inversion to generate HDR panoramas.
> 3. We use  [this paper, code](https://elliottwu.com/projects/20_unsup3d/) to generate faces.  When you have both HDR panorams and 3D faces, you can render the faces with blender app or blender script. I suggest this [blender script](https://github.com/yuki-koyama/blender-cli-rendering).

Thank you very much for your quick reply.
I am a green hand on light analysis. 
Is there any python or c++ code (a link if possible) that I can use to calculate the light direction and intensity from an HDR panorama?

**Comment by Wanggcong** [comment]
> > Thank you for you attention.
> > 
> > 1. Given a LDR FOV image, we generate a HDR panorama. The HDR panorama is a HDR spherical image that provides lighting direction and HDR provides lighting intensity.
> > 2. Since our model uses GAN inversion, the size of FOV is not limited to a fixed size, see the [framework](https://style-light.github.io/index). Given a FOV, we project it into a panorama, where black areas are invisible regions and visible pixels are from FOV. We then use GAN inversion to generate HDR panoramas.
> > 3. We use  [this paper, code](https://elliottwu.com/projects/20_unsup3d/) to generate faces.  When you have both HDR panorams and 3D faces, you can render the faces with blender app or blender script. I suggest this [blender script](https://github.com/yuki-koyama/blender-cli-rendering).
> 
> Thank you very much for your quick reply. I am a green hand on light analysis. Is there any python or c++ code (a link if possible) that I can use to calculate the light direction and intensity from an HDR panorama?

Sorry, I am not quite sure if I understand your question. As far as I can see, HDR panorama can be directly regarded lighting direction and intensity. Consider an object which is place at the center of a panorama (sphere), each pixel of the panorama can be regarded as a lighting ray to the center. The pixel value is the intensity. Please let me know if I misunderstand your question.

**Comment by yang-ruixin** [comment]
> > > Thank you for you attention.
> > > 
> > > 1. Given a LDR FOV image, we generate a HDR panorama. The HDR panorama is a HDR spherical image that provides lighting direction and HDR provides lighting intensity.
> > > 2. Since our model uses GAN inversion, the size of FOV is not limited to a fixed size, see the [framework](https://style-light.github.io/index). Given a FOV, we project it into a panorama, where black areas are invisible regions and visible pixels are from FOV. We then use GAN inversion to generate HDR panoramas.
> > > 3. We use  [this paper, code](https://elliottwu.com/projects/20_unsup3d/) to generate faces.  When you have both HDR panorams and 3D faces, you can render the faces with blender app or blender script. I suggest this [blender script](https://github.com/yuki-koyama/blender-cli-rendering).
> > 
> > 
> > Thank you very much for your quick reply. I am a green hand on light analysis. Is there any python or c++ code (a link if possible) that I can use to calculate the light direction and intensity from an HDR panorama?
> 
> Sorry, I am not quite sure if I understand your question. As far as I can see, HDR panorama can be directly regarded lighting direction and intensity. Consider an object which is place at the center of a panorama (sphere), each pixel of the panorama can be regarded as a lighting ray to the center. The pixel value is the intensity. Please let me know if I misunderstand your question.

<img width="256" alt="20150101_8624_test_tmp" src="https://user-images.githubusercontent.com/39927800/235081060-be4fffd4-b849-4df9-a455-e464c41846e2.png">
<img width="256" alt="20150111_8953_test" src="https://user-images.githubusercontent.com/39927800/235081085-54474e04-6d66-42ec-a020-56fe1c8dd755.png">
Thank you again for your kind reply.
Here is the generated panoramas. I am just trying to understand these figures.
For the panorama above, the three red circles are the predicted light sources, correct?
For the second panorama, I can make a conclusion that the light from right is stronger than the light from left (I mean in terms of the input FOV image, the light source from right of the image is stronger). Am I right?

**Comment by Wanggcong** [comment]
Thank you. 1) Sure, there are lighting sources. 2)  That is right. In fact, since it is a panorama (sphere), the left and the right are stitched.

**Comment by yang-ruixin** [comment]
> Thank you. 1) Sure, there are lighting sources. 2) That is right. In fact, since it is a panorama (sphere), the left and the right are stitched.

Thank you very much for your kind reply.
