### ISSUE TITLE
The light intensity of the HDR panorama needs to be multiplied by a coefficient to adjust, otherwise it will be too dark. 

### ISSUE THREAD

**Issue by chiyueOfgit** [Wanggcong/StyleLight#8]
It is a great honor for me to study your results.After I estimate the HDR panorama with the model, I use it to render virtual objects in blender.
I've noticed that rendering directly from the output results in very dark renders. I had to multiply the light intensity by a factor of 100 to get a visually ideal rendering.

![1](https://github.com/Wanggcong/StyleLight/assets/61923449/9cace7b1-2162-4dff-baf9-5091c586d0f6)

I would like to know what are the reasons for this? Looking forward to your reply!

**Comment by Wanggcong** [comment]
Thank you for your question. I think the reason could be the material and the lighting intensity. It depends on how much lighting rays the material reflects.

**Comment by Wanggcong** [comment]
I closed the issue. If you have other questions, you could re-open or raise a new issue.
